version: '3.8'
services:
  containerbase-db:
    image: postgres:${POSTGRES_VERSION:-latest}
    restart: always
    hostname: containerbase-db
    container_name: containerbase-db
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: containerbase
    command: ['postgres', '-c', 'wal_level=logical', "-c", "log_statement=all"]
    healthcheck:
      test: ['CMD', 'psql', '-U', 'postgres', '-c', 'SELECT 1']
      interval: 5s
      timeout: 5s
      retries: 15
    volumes:
      - ./scripts/postgres-init/init.sql:/docker-entrypoint-initdb.d/10-init.sql
      - ./volumes/containerbase-db/data:/var/lib/postgresql/data
    networks:
      - ${GLOBAL_NETWORK:-containerbase}
